Repository astronomer/astro-cli, pull requests merged in 2022-12, with the labels that each got.

#941 fix SQL CONN deprecation warnings
  airflow/docker_test.go
  airflow/include/composeyml.go
  settings/testfiles/airflow_settings_export.yaml
Labels: team/ma-practitioner

#969 return error from api
  cloud/deployment/deployment.go
  cloud/deployment/deployment_test.go
Labels: team/ma-practitioner, app/astro-cli

#962 moved include package logic into airflow.go
  .pre-commit-config.yaml
  .yamllint
  airflow/airflow.go
  airflow/container.go
  airflow/docker.go
  airflow/include/advancedexampledag.py
  airflow/include/astronomermonitoringdag.py
  airflow/include/basicexampledag.py
  airflow/include/composeyml.yml
  airflow/include/dagintegritytest.py
  airflow/include/dagintegritytestdefault.go
  airflow/include/dagintegritytestdefault.py
  airflow/include/dockerfile
  airflow/include/dockerfile.go
  airflow/include/dockerignore
  airflow/include/dockerignore.go
  airflow/include/gitignore
  airflow/include/gitignore.go
  airflow/include/readme
  airflow/include/settingsyml.yml
  cloud/deploy/deploy.go
Labels: team/ma-practitioner, app/astro-cli

#942 create deployments from YAML or JSON file
  astro-client/astro.go
  astro-client/astro_test.go
  astro-client/mocks/Client.go
  astro-client/mutations.go
  astro-client/queries.go
  astro-client/types.go
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
  cloud/deployment/inspect/inspect.go
  cloud/deployment/inspect/inspect_test.go
  cloud/deployment/workerqueue/workerqueue.go
  cloud/deployment/workerqueue/workerqueue_test.go
  cmd/cloud/deployment.go
  cmd/cloud/deployment_inspect_test.go
  cmd/cloud/deployment_test.go
  go.mod
  go.sum
Labels: team/ma-practitioner, app/astro-cli

#980 Adds .airflowignore
  airflow/airflow.go
  airflow/airflow_test.go
Labels: kind/enhancement

#968 Update deployment from YAML or JSON file
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
  cmd/cloud/deployment.go
  cmd/cloud/deployment_test.go
Labels: team/ma-practitioner, app/astro-cli

#988 improve error messaging
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
Labels: team/ma-practitioner, app/astro-cli
