Repository astronomer/astro-cli, pull requests merged in 2023-01, with the labels that each got.

#993 inspect can create templates
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/inspect/inspect.go
  cloud/deployment/inspect/inspect_test.go
  cmd/cloud/deployment_inspect.go
  cmd/cloud/deployment_inspect_test.go
Labels: team/ma-practitioner, app/astro-cli, 1.9.0

#989 improve validation on create or update from file
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
Labels: team/ma-practitioner, app/astro-cli

#1001 infer `isdefault` from queue name
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
  cloud/deployment/inspect/inspect.go
  cloud/deployment/inspect/inspect_test.go
Labels: team/ma-practitioner, app/astro-cli, 1.9.0

#999 fix missing fields in Create and Update deployment output
  astro-client/mutations.go
  cloud/deployment/deployment.go
Labels: team/ma-practitioner, app/astro-cli, 1.9.0

#996 create KE or CE deployments
  astro-client/types.go
  cloud/deployment/deployment.go
  cloud/deployment/deployment_test.go
  cloud/deployment/inspect/inspect.go
  cloud/deployment/inspect/inspect_test.go
  cmd/cloud/deployment.go
  cmd/cloud/deployment_test.go
Labels: team/ma-practitioner, app/astro-cli

#1008 932 ke create from file
  astro-client/types.go
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
  cloud/deployment/inspect/inspect.go
  cloud/deployment/inspect/inspect_test.go
  cloud/deployment/workerqueue/workerqueue.go
  cloud/deployment/workerqueue/workerqueue_test.go
  cmd/cloud/deployment_test.go
Labels: team/ma-practitioner, app/astro-cli

#1013 update deployment from file blocks changing cluster
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
  cmd/cloud/deployment.go
  cmd/cloud/deployment_test.go
Labels: team/ma-practitioner, app/astro-cli, 1.9.0

#1011 updates from file can toggle executor
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/fromfile/fromfile_test.go
Labels: team/ma-practitioner, app/astro-cli

#1014 worker queue create command supports KE deployments
  cloud/deployment/workerqueue/workerqueue.go
  cloud/deployment/workerqueue/workerqueue_test.go
Labels: team/ma-practitioner, app/astro-cli

#1017 wq update command works with KE
  cloud/deployment/fromfile/fromfile.go
  cloud/deployment/workerqueue/workerqueue.go
  cloud/deployment/workerqueue/workerqueue_test.go
  cmd/cloud/deployment_workerqueue.go
  cmd/cloud/deployment_workerqueue_test.go
Labels: team/ma-practitioner, app/astro-cli

#1027 Update readme initialized by astro dev init
  airflow/include/readme
Labels: kind/bug-misleading

#1040 deployment queries return `description`
  astro-client/queries.go
Labels: kind/bug-broken, app/astro-cli, team/runtime-management
